### ISSUE TITLE
Expo 27: ExponentGLObjectManager.createObjectAsync is not available

### ISSUE THREAD

**Issue by wcandillon** [gre/webgltexture-loader#3]
I just upgraded to expo 27 and I'm hitting the warning/error at https://github.com/gre/webgltexture-loader/blob/34eaa88df6c28b0cbde82af1f29ca6c2a15938f2/packages/webgltexture-loader-expo/src/ExponentGLObjectTextureLoader.js#L11

Was the NativeModule renamed or something?

**Comment by wcandillon** [comment]
😍 Let me know when a new version is available on npm, I'm excited :)

**Comment by gre** [comment]
it's available on npm.

```
$ yarn list gl-react* expo webgltexture-loader*
yarn list v1.3.2
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ expo@27.0.1
├─ gl-react-expo@3.16.3
├─ gl-react@3.15.0
├─ webgltexture-loader-expo@0.10.0
├─ webgltexture-loader-ndarray@0.9.0
└─ webgltexture-loader@0.6.0
✨  Done in 0.61s.
```

![camera](https://user-images.githubusercontent.com/211411/39763444-5c48f096-52dd-11e8-92a1-51475980cd30.gif)

**Comment by gre** [comment]
the way to implement it has changed a bit:

- need to ask camera permission before anything : https://github.com/gre/gl-react/blob/master/examples/expo-gl-react-camera-effects/src/App.js#L72-L73
- need to use Expo's `<Camera>` https://github.com/gre/gl-react/blob/master/examples/expo-gl-react-camera-effects/src/GLCamera.js#L45-L61

**Comment by wcandillon** [comment]
It works great, thanks a lot 🙌🏻

**Comment by wcandillon** [comment]
@gre Do you have an example of loading an image (local or remote) with this new version? I'm getting a crash. I tried to debug the loader but unsuccessfully. `canLoad` returns true and then the app crash and as far I know, no other method in the load is called 🤔

Thank you for your support.

**Comment by gre** [comment]
mmh the cookbook seems to work fine: https://github.com/gre/gl-react/blob/master/examples/cookbook-rn-shared/examples/diamondcrop/index.js#L31

need to do 

`{{ uri }}`

which i'm not sure if it's a regression or not (to not being able to directly pass the url)

**Comment by wcandillon** [comment]
Hi Gaëtan,

Thank you for your support. Thanks to your example I was able to pin down
the regression: local images don't work anymore. Maybe it's a read access
problem? I will take a look again at the loader.

Kind regards,

William

**Comment by gre** [comment]
oh weird, yeah i'm not sure i've actually tested local images

**Comment by wcandillon** [comment]
localFile() is called and seem to crash but I cannot debug it:
https://github.com/gre/webgltexture-loader/blob/master/packages/webgltexture-loader-expo/src/ExpoModuleTextureLoader.js#L53
Any ideas on how I could debug this further? So far I've been adding
console.log() call to the function but I'm getting strange results.

**Comment by gre** [comment]
found it https://github.com/gre/webgltexture-loader/commit/3954f920f07d819ce59ad02c1dc8bfa6c7ef77ea
